name: React Storefront CI

on:
  push:
    branches: [canary]
  pull_request:
    branches: [canary]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Run Tests
        run: npm run test

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          command: build
          Dockerfile: ./Dockerfile
          repository: shivakrishna99/saleordashboard
          tags: latest

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          command: push
          repository: shivakrishna99/saleordashboard
          tags: latest
          containerRegistry: Docker-Hub-Connection
